// src/utils/indianCities.js
export const indianCities = [
  "Agar Malwa",
  "Aizawl",
  "Ajmer",
  "Alappuzha",
  "Aligarh",
  "Alirajpur",
  "Ambala",
  "Ambedkar Nagar",
  "Amethi",
  "Amravati",
  "Anantapur",
  "Anjaw",
  "Anuppur",
  "Araria",
  "Arwal",
  "Ashoknagar",
  "Aurangabad",
  "Auraiya",
  "Azamgarh",
  "Badaun",
  "Bagalkot",
  "Baghpat",
  "Baharampur",
  "Baleshwar",
  "Balangir",
  "Baloda Bazar",
  "Balrampur",
  "Balrampur",
  "Banda",
  "Bankura",
  "Banswara",
  "Baran",
  "Barmer",
  "Barnala",
  "Barwani",
  "Basirhat",
  "Bastar",
  "Bastar",
  "Bathinda",
  "Bemetara",
  "Bengal",
  "Bhagalpur",
  "Bhandara",
  "Bhind",
  "Bhopal",
  "Bilaspur",
  "Bilaspur",
  "Bundi",
  "Burhanpur",
  "Cachar",
  "Chamoli",
  "Champawat",
  "Champhai",
  "Chandigarh",
  "Chandrapur",
  "Chhatarpur",
  "Chhindwara",
  "Chiruachandpur",
  "Churachandpur",
  "Churu",
  "Cuddalore",
  "Dadra and Nagar Haveli",
  "Daman",
  "Daman and Diu",
  "Damoh",
  "Darbhanga",
  "Darjiling",
  "Dausa",
  "Dewas",
  "Dhamtari",
  "Dhanbad",
  "Dhar",
  "Dharwad",
  "Dibrugarh",
  "Dimapur",
  "Dindori",
  "Doda",
  "Durg",
  "East District",
  "East Garo Hills",
  "East Jaintia Hills",
  "East Kameng",
  "East Khasi Hills",
  "East Siang",
  "Etah",
  "Etawah",
  "Faizabad",
  "Faridabad",
  "Fatehabad",
  "Fatehgarh Sahib",
  "Fazilka",
  "Firozabad",
  "Gadchiroli",
  "Gajapati",
  "Ganjam",
  "Garhwa",
  "Gaya",
  "Girsomnath",
  "Giridih",
  "Goalpara",
  "Golaghat",
  "Gonda",
  "Gorakhpur",
  "Gujarat",
  "Gurdaspur",
  "Gurgaon",
  "Gwalior",
  "Hailakandi",
  "Hazaribagh",
  "Himachal Pradesh",
  "Hisar",
  "Hoshiarpur",
  "Hyderabad",
  "Idukki",
  "Imphal East",
  "Imphal West",
  "Indore",
  "Jabalpur",
  "Jagatsinghapur",
  "Jagtial",
  "Jalaun",
  "Jalgaon",
  "Jalna",
  "Jalore",
  "Jammu",
  "Jamshedpur",
  "Janjgir - Champa",
  "Jhabua",
  "Jhansi",
  "Jhargram",
  "Jind",
  "Jorhat",
  "Kachchh",
  "Kaimur (Bhabua)",
  "Kangra",
  "Kapurthala",
  "Karbi Anglong",
  "Karimganj",
  "Kasaragod",
  "Kathua",
  "Kavali",
  "Khammam",
  "Khandwa (East Nimar)",
  "Kharagpur",
  "Kheda",
  "Kishanganj",
  "Koch Bihar",
  "Kolkata",
  "Koppal",
  "Koraput",
  "Kota",
  "Kullu",
  "Kurnool",
  "Ladakh",
  "Lakhimpur",
  "Lalitpur",
  "Lawngtlai",
  "Leh",
  "Ludhiana",
  "Madhubani",
  "Madurai",
  "Mahabubabad",
  "Mahbubnagar",
  "Maharashtra",
  "Mandi",
  "Mandsaur",
  "Mansa",
  "Mathura",
  "Mayurbhanj",
  "Medak",
  "Medchal-Malkajgiri",
  "Mewat",
  "Mirzapur",
  "Mizoram",
  "Mokokchung",
  "Mumbai",
  "Mumbai Suburban",
  "Murshidabad",
  "Muzaffarpur",
  "Nagapattinam",
  "Nagarkurnool",
  "Nagaon",
  "Nanded",
  "Narmada",
  "Narsinghpur",
  "Nashik",
  "Navsari",
  "Neemuch",
  "Niwari",
  "North East",
  "North Goa",
  "North Tripura",
  "North Twenty Four Parganas",
  "North West",
  "North West Delhi",
  "Odisha",
  "Pachmarhi",
  "Palakkad",
  "Pallakad",
  "Pali",
  "Panchkula",
  "Pune",
  "Panipat",
  "Panna",
  "Patiala",
  "Pauri Garhwal",
  "Purnia",
  "Purulia",
  "Rae Bareli",
  "Raigarh",
  "Raipur",
  "Rajnandgaon",
  "Ranchi",
  "Ratlam",
  "Ratnagiri",
  "Rayagada",
  "Rewa",
  "Rohtak",
  "Saharanpur",
  "Sambalpur",
  "Sangli",
  "Sangrur",
  "Sant Kabir Nagar",
  "Satna",
  "Shahdol",
  "Shajapur",
  "Sheopur",
  "Shimla",
  "Sirmaur",
  "Sivaganga",
  "Solan",
  "Sonbhadra",
  "Sonipat",
  "South Goa",
  "South Tripura",
  "South West Khasi Hills",
  "Srikakulam",
  "Sundargarh",
  "Surajpur",
  "Surat",
  "Suryapet",
  "Tawang",
  "Tirap",
  "Tirunelveli",
  "Tiruppur",
  "Tiruchirappalli",
  "Udhampur",
  "Udaipur",
  "Uttar Dinajpur",
  "Uttar Bastar Kanker",
  "Uttarkashi",
  "Vadodara",
  "Vaishali",
  "Vellore",
  "Vidisha",
  "Vikarabad",
  "West Garo Hills",
  "West Jaintia Hills",
  "West Kameng",
  "West Khasi Hills",
  "West Tripura",
  "Yadadri",
  "Yavatmal",
  "Zunheboto",
];
